# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes of the truth seeker programmer
name: Merkulov Maksim
email: merkulovmx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Considering I am not working with old physical phone systems.
  I decided to make a new blog with my accumulated experience. 
  It is the link about it [merkulovmx.gitlab.io](https://merkulovmx.gitlab.io)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://merkulovmx.github.io" # the base hostname & protocol for your site
github_username:  DomenZero
linkedin_username: maksim-merkulov

# Build settings
markdown: kramdown
plugins:
    - jekyll-sitemap
    - jemoji
